# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_tab_setup.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(511, 341)
        Form.setWindowTitle("Form")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.warning_label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.warning_label.setFont(font)
        self.warning_label.setWordWrap(True)
        self.warning_label.setObjectName("warning_label")
        self.verticalLayout.addWidget(self.warning_label)
        self.settings_group = QtWidgets.QGroupBox(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.settings_group.setFont(font)
        self.settings_group.setTitle("Settings")
        self.settings_group.setObjectName("settings_group")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.settings_group)
        self.gridLayout_2.setContentsMargins(-1, 13, 6, 6)
        self.gridLayout_2.setHorizontalSpacing(4)
        self.gridLayout_2.setVerticalSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.settings_class_label = QtWidgets.QLabel(self.settings_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settings_class_label.sizePolicy().hasHeightForWidth())
        self.settings_class_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.settings_class_label.setFont(font)
        self.settings_class_label.setText("Name of current students class")
        self.settings_class_label.setObjectName("settings_class_label")
        self.gridLayout_2.addWidget(self.settings_class_label, 0, 0, 1, 1)
        self.settings_class_edit = QtWidgets.QLineEdit(self.settings_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settings_class_edit.sizePolicy().hasHeightForWidth())
        self.settings_class_edit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.settings_class_edit.setFont(font)
        self.settings_class_edit.setText("")
        self.settings_class_edit.setObjectName("settings_class_edit")
        self.gridLayout_2.addWidget(self.settings_class_edit, 0, 1, 1, 1)
        self.settings_class_adv_button = QtWidgets.QToolButton(self.settings_group)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.settings_class_adv_button.setFont(font)
        self.settings_class_adv_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.settings_class_adv_button.setText("|")
        self.settings_class_adv_button.setIconSize(QtCore.QSize(2, 16))
        self.settings_class_adv_button.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.settings_class_adv_button.setObjectName("settings_class_adv_button")
        self.gridLayout_2.addWidget(self.settings_class_adv_button, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.settings_group)
        self.update_group = QtWidgets.QGroupBox(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.update_group.setFont(font)
        self.update_group.setTitle("Update libraries, examples, software")
        self.update_group.setObjectName("update_group")
        self.gridLayout = QtWidgets.QGridLayout(self.update_group)
        self.gridLayout.setContentsMargins(-1, 13, 9, 5)
        self.gridLayout.setVerticalSpacing(4)
        self.gridLayout.setObjectName("gridLayout")
        self.update_zip_button = QtWidgets.QPushButton(self.update_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.update_zip_button.sizePolicy().hasHeightForWidth())
        self.update_zip_button.setSizePolicy(sizePolicy)
        self.update_zip_button.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.update_zip_button.setFont(font)
        self.update_zip_button.setText("Update from zip file")
        self.update_zip_button.setObjectName("update_zip_button")
        self.gridLayout.addWidget(self.update_zip_button, 2, 2, 1, 1)
        self.update_label = QtWidgets.QLabel(self.update_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.update_label.sizePolicy().hasHeightForWidth())
        self.update_label.setSizePolicy(sizePolicy)
        self.update_label.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.update_label.setFont(font)
        self.update_label.setLineWidth(1)
        self.update_label.setText("Version of the currently installed software:  ")
        self.update_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.update_label.setWordWrap(True)
        self.update_label.setIndent(1)
        self.update_label.setObjectName("update_label")
        self.gridLayout.addWidget(self.update_label, 0, 0, 1, 3)
        self.update_server_button = QtWidgets.QPushButton(self.update_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.update_server_button.sizePolicy().hasHeightForWidth())
        self.update_server_button.setSizePolicy(sizePolicy)
        self.update_server_button.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.update_server_button.setFont(font)
        self.update_server_button.setText("Update from EduSense")
        self.update_server_button.setObjectName("update_server_button")
        self.gridLayout.addWidget(self.update_server_button, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.update_group)
        self.firmware_group = QtWidgets.QGroupBox(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.firmware_group.setFont(font)
        self.firmware_group.setTitle("Devices maintenance")
        self.firmware_group.setObjectName("firmware_group")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.firmware_group)
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_3.setContentsMargins(-1, 13, -1, 6)
        self.gridLayout_3.setHorizontalSpacing(4)
        self.gridLayout_3.setVerticalSpacing(3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.service_button = QtWidgets.QPushButton(self.firmware_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.service_button.sizePolicy().hasHeightForWidth())
        self.service_button.setSizePolicy(sizePolicy)
        self.service_button.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.service_button.setFont(font)
        self.service_button.setText("Open panel (for advanced users!)")
        self.service_button.setObjectName("service_button")
        self.gridLayout_3.addWidget(self.service_button, 0, 0, 2, 1)
        self.gridLayout_3.setColumnStretch(0, 1)
        self.verticalLayout.addWidget(self.firmware_group)
        self.verticalLayout.setStretch(0, 8)
        self.verticalLayout.setStretch(1, 8)
        self.verticalLayout.setStretch(2, 10)
        self.verticalLayout.setStretch(3, 10)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        self.warning_label.setText(_translate("Form", "All setting below are ONLY for experienced users. Please, don\'t touch it, if you don\'t know what you are doing!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
